# 1. The Cloud Database Connection
spring.datasource.url=jdbc:postgresql://ep-gentle-tooth-a1yo6vd2-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CsTl4b7oyqQv

# 2. Hibernate Settings (Builds your tables automatically)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true